"use client";

import { useState, useEffect } from "react";
import { CSS, fmtTime, fmtDateLong } from "@/lib/constants";
import { useLang } from "@/lib/i18n";
import { calcStreak, TIER_LIMITS } from "@/lib/data";
import AdherenceChart from "@/components/AdherenceChart";
import AdherenceCalendar from "@/components/AdherenceCalendar";
import { SideEffectSummary } from "@/components/SideEffectTracker";
import { JournalMiniCalendar, JournalEntrySheet, JournalTimeline, getJournalEntry } from "@/components/HealthJournal";
import { Pill, BarChart3, TrendingUp, TrendingDown, Lightbulb, Clock, ClipboardList, Users, User, Bell, DollarSign, FileText, Stethoscope, BookOpen, CalendarDays, Download } from "lucide-react";

function Ico({ children, ...props }) {
  return <span style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", lineHeight: 1, flexShrink: 0 }} {...props}>{children}</span>;
}

export default function ReportsTab({ logs, meds, plan, onNavigate, onViewFamily }) {
  const { t } = useLang();
  const [showHistory, setShowHistory] = useState(false);
  const [journalDate, setJournalDate] = useState(null);
  const [journalEntries, setJournalEntries] = useState([]);
  const limits = TIER_LIMITS[plan] || TIER_LIMITS.free;
  const today = new Date();

  useEffect(() => {
    try { setJournalEntries(JSON.parse(localStorage.getItem("mt_journal") || "[]")); } catch { setJournalEntries([]); }
  }, [showHistory]);

  const streak = calcStreak(logs, meds);
  const grouped = {};
  logs.forEach(l => { const d = l.taken_at?.split("T")[0]; if (d) { if (!grouped[d]) grouped[d]=[]; grouped[d].push(l); } });
  const daysTracked = Object.keys(grouped).length;
  const totalDoses = logs.length;
  const adherence = daysTracked > 0 ? Math.round((totalDoses / (daysTracked * meds.reduce((s,m) => s + (m.times_per_day || 1), 0))) * 100) : 0;

  function perMedAdherence() {
    return meds.map(med => {
      const medLogs = logs.filter(l => l.medication_id === med.id);
      const expected = med.course_duration_days * (med.times_per_day || 1);
      const pct = expected > 0 ? Math.round((medLogs.length / expected) * 100) : 0;
      return { ...med, taken: medLogs.length, expected, pct: Math.min(pct, 100) };
    });
  }

  function generateDoctorSummary() {
    const pm = perMedAdherence();
    const dateStr = today.toLocaleDateString("en", { year:"numeric", month:"long", day:"numeric" });
    let txt = `ADHERA — Medication Adherence Report\n`;
    txt += `Date: ${dateStr}\n`;
    txt += `Plan: ${plan.charAt(0).toUpperCase()+plan.slice(1)}\n`;
    txt += `─────────────────────\n\n`;
    txt += `Overall Adherence: ${adherence}%\n`;
    txt += `Current Streak: ${streak} day${streak!==1?"s":""}\n`;
    txt += `Days Tracked: ${daysTracked}\n`;
    txt += `Total Doses Logged: ${totalDoses}\n\n`;
    txt += `PER-MEDICATION BREAKDOWN:\n`;
    pm.forEach(m => {
      const status = m.pct >= 80 ? "Good" : m.pct >= 50 ? "Fair" : "Poor";
      txt += `• ${m.name} (${m.dosage_amount} ${m.dosage_unit}) — ${m.pct}% [${status}]\n`;
      txt += `  Taken ${m.taken}/${m.expected} expected doses\n`;
    });
    txt += `\n─────────────────────\n`;
    txt += `Generated by Adhera · adhera.app`;
    return txt;
  }

  async function shareWithDoctor() {
    const text = generateDoctorSummary();
    if (navigator.share) {
      try {
        await navigator.share({ title: "Adhera Medical Report", text });
      } catch (e) { if (e.name !== "AbortError") fallbackCopy(text); }
    } else {
      fallbackCopy(text);
    }
  }

  function fallbackCopy(text) {
    navigator.clipboard?.writeText(text).then(() => {
      alert("Report copied to clipboard! Paste it into WhatsApp or email to send to your doctor.");
    }).catch(() => {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      alert("Report copied to clipboard!");
    });
  }

  function drawBarChart(canvas, data, label, color) {
    const ctx = canvas.getContext("2d");
    const w = canvas.width, h = canvas.height;
    const count = data.length;
    const pad = { t: 40, r: 24, b: count > 6 ? 80 : 56, l: 56 };
    const cw = w - pad.l - pad.r, ch = h - pad.t - pad.b;
    ctx.clearRect(0, 0, w, h);

    const bgGrad = ctx.createLinearGradient(0, 0, 0, h);
    bgGrad.addColorStop(0, "#FAFBFC");
    bgGrad.addColorStop(1, "#F0F2F5");
    ctx.fillStyle = bgGrad;
    ctx.beginPath();
    ctx.roundRect(0, 0, w, h, 12);
    ctx.fill();

    ctx.fillStyle = "#0F172A";
    ctx.font = "600 15px Inter, system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText(label, w/2, 24);

    const maxVal = Math.max(...data.map(d => d.val), 10);
    const gap = cw / (count + 1);
    const barW = Math.min(gap * 0.55, 44);
    const labelFontSize = count > 6 ? 9 : count > 4 ? 10 : 11;

    ctx.strokeStyle = "#E2E8F0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(pad.l, pad.t);
    ctx.lineTo(pad.l, pad.t + ch);
    ctx.lineTo(pad.l + cw, pad.t + ch);
    ctx.stroke();

    const gridSteps = [0, 25, 50, 75, 100];
    gridSteps.forEach(pct => {
      if (pct > maxVal) return;
      const gy = pad.t + ch - (pct / maxVal) * ch;
      if (pct > 0) {
        ctx.strokeStyle = "#F1F5F9";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(pad.l, gy);
        ctx.lineTo(pad.l + cw, gy);
        ctx.stroke();
      }
      ctx.fillStyle = "#94A3B8";
      ctx.font = "10px Inter, system-ui, sans-serif";
      ctx.textAlign = "right";
      ctx.fillText(pct + "%", pad.l - 8, gy + 3.5);
    });

    data.forEach((d, i) => {
      const x = pad.l + gap * (i + 1) - barW/2;
      const bh = Math.max((d.val / maxVal) * ch, 2);
      const y = pad.t + ch - bh;

      const barGrad = ctx.createLinearGradient(x, y, x + barW, pad.t + ch);
      if (d.val >= 80) { barGrad.addColorStop(0, "#34D399"); barGrad.addColorStop(1, "#059669"); }
      else if (d.val >= 50) { barGrad.addColorStop(0, "#FBBF24"); barGrad.addColorStop(1, "#D97706"); }
      else { barGrad.addColorStop(0, "#F87171"); barGrad.addColorStop(1, "#DC2626"); }
      ctx.fillStyle = barGrad;
      ctx.beginPath();
      ctx.roundRect(x, y, barW, bh, [4,4,0,0]);
      ctx.fill();

      const pctText = d.val + "%";
      ctx.font = "700 11px Inter, system-ui, sans-serif";
      const tw = ctx.measureText(pctText).width + 14;
      const th = 20;
      const tx = x + barW/2;
      const ty = y - 6;

      ctx.fillStyle = "rgba(255,255,255,.92)";
      ctx.beginPath();
      ctx.roundRect(tx - tw/2, ty - th + 5, tw, th, [6,6,6,6]);
      ctx.fill();
      ctx.fillStyle = "#0F172A";
      ctx.textAlign = "center";
      ctx.fillText(pctText, tx, ty + 5);

      ctx.fillStyle = "#475569";
      ctx.font = `${labelFontSize}px Inter, system-ui, sans-serif`;
      ctx.textAlign = "center";
      ctx.save();
      if (count > 6) {
        ctx.translate(x + barW/2, pad.t + ch + 14);
        ctx.rotate(-Math.PI / 6);
        ctx.fillText(d.label, 0, 0);
      } else {
        ctx.fillText(d.label, x + barW/2, pad.t + ch + 18);
      }
      ctx.restore();
    });
  }

  async function generatePdfReport() {
    const pm = perMedAdherence();

    const weekDays = [];
    for (let i = 6; i >= 0; i--) {
      const d = new Date(today);
      d.setDate(d.getDate() - i);
      const ds = d.toISOString().split("T")[0];
      const dayLogs = logs.filter(l => l.taken_at?.startsWith(ds));
      const dailyExp = meds.reduce((s,m) => s + (m.times_per_day || 1), 0);
      const pct = dailyExp > 0 ? Math.round((dayLogs.length / dailyExp) * 100) : 0;
      weekDays.push({ label: d.toLocaleDateString("en",{weekday:"short"}), val: Math.min(pct,100) });
    }

    const chartCanvas1 = document.createElement("canvas");
    chartCanvas1.width = 720;
    chartCanvas1.height = 340;
    drawBarChart(chartCanvas1, pm.map(m => ({ label: m.name.length > 12 ? m.name.slice(0,12)+"…" : m.name, val: m.pct })), "Adherence by Medication", "#2563EB");

    const chartCanvas2 = document.createElement("canvas");
    chartCanvas2.width = 720;
    chartCanvas2.height = 300;
    drawBarChart(chartCanvas2, weekDays, "Daily Adherence (Last 7 Days)", "#059669");

    const chart1 = chartCanvas1.toDataURL("image/png");
    const chart2 = chartCanvas2.toDataURL("image/png");

    function medStatus(pct) {
      return pct >= 80 ? "Good" : pct >= 50 ? "Fair" : "Poor";
    }

    function timeOfDayAnalysis() {
      const slots = { Morning: 0, Afternoon: 0, Evening: 0, Night: 0 };
      logs.forEach(l => {
        const h = new Date(l.taken_at).getHours();
        if (h < 6) slots.Night++;
        else if (h < 12) slots.Morning++;
        else if (h < 18) slots.Afternoon++;
        else slots.Evening++;
      });
      const best = Object.entries(slots).sort((a,b) => b[1] - a[1])[0];
      return { slots, best: best ? best[0] : "—", bestCount: best ? best[1] : 0 };
    }

    const timeAnalysis = timeOfDayAnalysis();

    const activeMeds = meds.filter(m => m.active);
    const completedPct = activeMeds.length
      ? Math.round(activeMeds.reduce((s,m) => s + Math.min(Math.ceil((today-new Date(m.start_date).getTime())/86400000), m.course_duration_days) / m.course_duration_days, 0) / activeMeds.length * 100)
      : 0;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<title>Adhera Medical Report</title>
<style>
  @page{size:A4;margin:18mm 16mm}
  *,:after,:before{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Inter,system-ui,sans-serif;color:#0f172a;line-height:1.5;padding:0;max-width:100vw;overflow-x:hidden;background:#f1f5f9;-webkit-font-smoothing:antialiased}
  img{max-width:100%;height:auto;display:block}

  .report-wrap{max-width:820px;margin:0 auto;background:#fff;min-height:100vh;padding:24px 32px 48px;overflow-x:hidden}
  @media(max-width:640px){.report-wrap{padding:16px 18px 32px}}

  .top-bar{display:flex;justify-content:space-between;align-items:center;padding-bottom:16px;margin-bottom:20px;border-bottom:1px solid #e2e8f0;flex-wrap:wrap;gap:8px}
  .top-bar-left{display:flex;align-items:center;gap:12px}
  .brand-mark{width:32px;height:32px;border-radius:8px;background:linear-gradient(135deg,#2563eb,#5856d6);display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;font-size:18px;flex-shrink:0}
  .brand-text{font-size:16px;font-weight:700;color:#0f172a;letter-spacing:-.3px}
  .top-bar-actions{display:flex;gap:8px}
  .btn-back,.btn-print{display:inline-flex;align-items:center;gap:8px;padding:12px 22px;border-radius:999px;font-size:14px;font-weight:600;cursor:pointer;text-decoration:none;transition:all .15s;font-family:inherit;line-height:1}
  .btn-back{background:linear-gradient(135deg,#2563eb,#5856d6);color:#fff;border:none;box-shadow:0 2px 10px rgba(37,99,235,.2)}
  .btn-back:hover{transform:translateY(-1px);box-shadow:0 4px 18px rgba(37,99,235,.3)}
  .btn-print{background:#fff;color:#475569;border:1.5px solid #e2e8f0}
  .btn-print:hover{background:#f8fafc;border-color:#cbd5e1}
  @media print{.top-bar{display:none!important}}

  .report-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:28px;padding-bottom:20px;border-bottom:2px solid #f1f5f9}
  .report-header-left h1{font-size:20px;font-weight:800;color:#2563eb;letter-spacing:-.4px;margin-bottom:2px}
  .report-header-left .tagline{font-size:12px;color:#64748b}
  .report-header-right{text-align:right}
  .report-header-right .date{font-size:14px;font-weight:700;color:#0f172a}
  .report-header-right .period{font-size:12px;color:#94a3b8;margin-top:2px}

  .patient-badge{display:grid;grid-template-columns:1fr 1fr;gap:10px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px 20px;margin-bottom:24px}
  .patient-badge-item{display:flex;flex-direction:column;gap:2px}
  .patient-badge-label{font-size:11px;font-weight:500;color:#94a3b8;text-transform:uppercase;letter-spacing:.4px}
  .patient-badge-value{font-size:15px;font-weight:700;color:#0f172a}

  .metric-row{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:12px;margin-bottom:28px}
  @media(max-width:480px){.metric-row{grid-template-columns:1fr 1fr;gap:8px}}
  .metric-card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px 12px;text-align:center}
  .metric-card-value{font-size:26px;font-weight:800;line-height:1.1}
  .metric-card-value.blue{color:#2563eb}
  .metric-card-value.green{color:#059669}
  .metric-card-value.orange{color:#d97706}
  .metric-card-value.purple{color:#7c3aed}
  .metric-card-label{font-size:11px;color:#64748b;margin-top:4px;line-height:1.3}

  .section-title{font-size:16px;font-weight:700;color:#0f172a;margin-bottom:14px;margin-top:28px;padding-bottom:8px;border-bottom:2px solid #e2e8f0;display:flex;align-items:center;gap:8px}
  .chart-wrap{margin:0 0 20px;text-align:center;padding:8px;background:#fafbfc;border:1px solid #e2e8f0;border-radius:12px}
  .chart-wrap img{max-width:100%;height:auto;border-radius:8px}

  .data-table{width:100%;border-collapse:collapse;font-size:13px;margin-bottom:20px}
  .data-table thead th{padding:10px 10px;text-align:left;font-weight:600;font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.3px;border-bottom:2px solid #e2e8f0;background:#f8fafc}
  .data-table tbody td{padding:10px;border-bottom:1px solid #f1f5f9;color:#334155}
  .data-table tbody tr:last-child td{border-bottom:none}
  .data-table .badge{margin-left:6px}
  .badge{display:inline-block;padding:3px 10px;border-radius:999px;font-size:11px;font-weight:600}
  .badge-good{background:#dcfce7;color:#059669}
  .badge-fair{background:#fef3c7;color:#d97706}
  .badge-poor{background:#fee2e2;color:#dc2626}

  .insight-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:24px}
  @media(max-width:480px){.insight-grid{grid-template-columns:1fr}}
  .insight-card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px}
  .insight-card-label{font-size:11px;font-weight:500;color:#94a3b8;text-transform:uppercase;letter-spacing:.4px;margin-bottom:4px}
  .insight-card-value{font-size:18px;font-weight:700;color:#0f172a}
  .insight-card-sub{font-size:12px;color:#64748b;margin-top:3px}

  .clinical-note{background:#f0f7ff;border:1px solid #bfdbfe;border-radius:12px;padding:18px 20px;margin-top:8px;margin-bottom:24px}
  .clinical-note-title{font-size:13px;font-weight:700;color:#1d4ed8;margin-bottom:6px}
  .clinical-note p{font-size:12px;color:#334155;line-height:1.6}

  .report-footer{margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px}
  .report-footer-text{font-size:10px;color:#94a3b8}
  .report-footer-logo{font-size:12px;font-weight:700;color:#94a3b8;letter-spacing:1px}
</style>
</head>
<body>

<div class="report-wrap">

<div class="top-bar">
  <div class="top-bar-left">
    <div class="brand-mark">A</div>
    <span class="brand-text">Adhera</span>
  </div>
  <div class="top-bar-actions">
    <button class="btn-print" onclick="window.print()">
      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/><path d="M6 14V6a2 2 0 012-2h8a2 2 0 012 2v8"/><path d="M6 18h12v4H6z"/></svg>
      Print
    </button>
    <a class="btn-back" onclick="window.close()">
      <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5"/><path d="M12 19l-7-7 7-7"/></svg>
      Close
    </a>
  </div>
</div>

<div class="report-header">
  <div class="report-header-left">
    <h1>Medication Adherence Report</h1>
    <div class="tagline">Comprehensive treatment summary generated by Adhera</div>
  </div>
  <div class="report-header-right">
    <div class="date">${today.toLocaleDateString("en",{year:"numeric",month:"long",day:"numeric"})}</div>
    <div class="period">All-time report</div>
  </div>
</div>

<div class="patient-badge">
  <div class="patient-badge-item">
    <span class="patient-badge-label">Plan</span>
    <span class="patient-badge-value">${plan.charAt(0).toUpperCase()+plan.slice(1)}</span>
  </div>
  <div class="patient-badge-item">
    <span class="patient-badge-label">Active Medications</span>
    <span class="patient-badge-value">${activeMeds.length}</span>
  </div>
  <div class="patient-badge-item">
    <span class="patient-badge-label">Current Streak</span>
    <span class="patient-badge-value">${streak} days</span>
  </div>
  <div class="patient-badge-item">
    <span class="patient-badge-label">Adherence Rate</span>
    <span class="patient-badge-value">${adherence}%</span>
  </div>
</div>

<div class="metric-row">
  <div class="metric-card">
    <div class="metric-card-value green">${adherence}%</div>
    <div class="metric-card-label">Overall<br>Adherence</div>
  </div>
  <div class="metric-card">
    <div class="metric-card-value blue">${streak}</div>
    <div class="metric-card-label">Best<br>Streak</div>
  </div>
  <div class="metric-card">
    <div class="metric-card-value orange">${daysTracked}</div>
    <div class="metric-card-label">Days<br>Tracked</div>
  </div>
  <div class="metric-card">
    <div class="metric-card-value purple">${totalDoses}</div>
    <div class="metric-card-label">Total<br>Doses</div>
  </div>
</div>

<div class="section-title">
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 8h6"/><path d="M9 12h6"/><path d="M9 16h4"/></svg>
  Adherence by Medication
</div>
<div class="chart-wrap"><img src="${chart1}" alt="Adherence by medication chart"/></div>

<table class="data-table">
  <thead>
    <tr><th>Medication</th><th>Dosage</th><th>Doses</th><th>Adherence</th></tr>
  </thead>
  <tbody>
    ${pm.map(m => `<tr>
      <td style="font-weight:600">${m.name}</td>
      <td>${m.dosage_amount} ${m.dosage_unit}</td>
      <td>${m.taken}/${m.expected}</td>
      <td>${m.pct}% <span class="badge badge-${medStatus(m.pct).toLowerCase()}">${medStatus(m.pct)}</span></td>
    </tr>`).join("")}
  </tbody>
</table>

<div class="section-title">
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
  Weekly Trend
</div>
<div class="chart-wrap"><img src="${chart2}" alt="Weekly adherence trend chart"/></div>

${limits.reports ? `
<div class="section-title">
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20V10"/><path d="M18 20V4"/><path d="M6 20v-4"/></svg>
  Clinical Insights
</div>
<div class="insight-grid">
  <div class="insight-card">
    <div class="insight-card-label">Best Adherence Time</div>
    <div class="insight-card-value">${timeAnalysis.best}</div>
    <div class="insight-card-sub">${timeAnalysis.bestCount} doses logged in this period</div>
  </div>
  <div class="insight-card">
    <div class="insight-card-label">Course Completion</div>
    <div class="insight-card-value">${completedPct}%</div>
    <div class="insight-card-sub">across ${activeMeds.length} active course${activeMeds.length!==1?"s":""}</div>
  </div>
  <div class="insight-card">
    <div class="insight-card-label">Dose Consistency</div>
    <div class="insight-card-value">${adherence >= 80 ? "Good" : adherence >= 50 ? "Moderate" : "Needs Attention"}</div>
    <div class="insight-card-sub">${adherence >= 80 ? "On track with treatment plan" : adherence >= 50 ? "Room for improvement" : "Significant doses missed"}</div>
  </div>
  <div class="insight-card">
    <div class="insight-card-label">Data Points</div>
    <div class="insight-card-value">${logs.length}</div>
    <div class="insight-card-sub">total dose logs recorded</div>
  </div>
</div>

<div class="clinical-note">
  <div class="clinical-note-title">For the Medical Professional</div>
  <p>This report summarizes the patient's self-reported medication adherence data tracked through Adhera. The patient has ${meds.length} medication${meds.length!==1?"s":""} on record with an overall adherence rate of <strong>${adherence}%</strong> across ${daysTracked} tracked days. ${pm.filter(m => m.pct < 80).length > 0 ? `Medications requiring attention: ${pm.filter(m => m.pct < 80).map(m => m.name).join(", ")}.` : "All medications are at or above the 80% adherence threshold."} The most consistent dosing occurs during the <strong>${timeAnalysis.best}</strong> period. Data is self-reported and may not reflect actual consumption. This report is intended to support clinical discussions and should not replace professional medical judgment.</p>
</div>
` : ""}

<div class="report-footer">
  <div class="report-footer-logo">ADHERA</div>
  <div class="report-footer-text">Medication Adherence Report · Generated ${today.toISOString().split("T")[0]} · Confidential</div>
</div>

</div>
</body></html>`;

    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    setTimeout(() => { win.print(); }, 800);
  }

  const pm = perMedAdherence();

  function AdherenceCard({ m, index }) {
    const colors = ["var(--ib1)","var(--ib4)","var(--ib5)","var(--ib3)","var(--ib2)","var(--ib6)"];
    const bg = colors[index % colors.length];
    return (
      <div style={{background:"var(--card)",borderRadius:"var(--rl)",padding:14,boxShadow:"var(--card-shadow)",display:"flex",alignItems:"center",gap:12}}>
        <div style={{width:30,height:30,borderRadius:8,background:bg,display:"grid",placeItems:"center",flexShrink:0}}><Ico><Pill size={16} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
        <div style={{flex:1,minWidth:0}}>
          <div style={{fontSize:15,fontWeight:600,color:"var(--t1)",marginBottom:2}}>{m.name}</div>
          <div style={{fontSize:12,color:"var(--t3)",marginBottom:4}}>{m.taken}/{m.expected} doses</div>
          <div className="prog"><div className="prog-fill" style={{width:`${m.pct}%`,background:m.pct>=80?"var(--teal2)":m.pct>=50?"var(--orange)":"var(--red)"}}/></div>
        </div>
        <div style={{fontSize:17,fontWeight:700,color:m.pct>=80?"var(--teal2)":m.pct>=50?"var(--orange)":"var(--red)",flexShrink:0}}>{m.pct}%</div>
      </div>
    );
  }

  return (
    <div className="scroll">
      <div className="nav-large">{t("reports.title")}</div>

      <div className="chips">
        <div className="chip blue"><div className="chip-val">{daysTracked}</div><div className="chip-lbl">{t("reports.daysTracked")}</div></div>
        <div className="chip green"><div className="chip-val">{adherence}%</div><div className="chip-lbl">{t("reports.adherenceRate")}</div></div>
        <div className="chip purple"><div className="chip-val">{streak}</div><div className="chip-lbl">{t("reports.bestStreak")}</div></div>
      </div>

      <div className="section">
        <div className="section-header">{t("reports.adherenceByMed")}</div>
        {meds.length === 0 ? (
          <div className="empty-state"><div className="empty-state-icon"><Ico><BarChart3 size={52} strokeWidth={1.5} color="var(--t2)"/></Ico></div><div className="empty-state-title">{t("reports.noData")}</div><div className="empty-state-sub">{t("reports.noDataSub")}</div></div>
        ) : (
          <div style={{display:"flex",flexDirection:"column",gap:10}}>
            {pm.map((m,i)=> <AdherenceCard key={m.id} m={m} index={i}/>)}
          </div>
        )}
      </div>

      <div className="section">
        <div className="section-header" style={{display:"flex",alignItems:"center",gap:8}}>
          <Ico><CalendarDays size={15} strokeWidth={2.2} color="var(--teal2)"/></Ico> Adherence calendar
        </div>
        <AdherenceCalendar logs={logs} meds={meds}/>
      </div>

      {limits.reports && (
        <div className="section">
          <div className="section-header" style={{display:"flex",alignItems:"center",gap:8}}>
            <Ico><TrendingUp size={15} strokeWidth={2.2} color="var(--teal2)"/></Ico> Detailed treatment analytics
          </div>
          <div style={{display:"flex",flexDirection:"column",gap:10}}>
            {meds.map(med => {
              const medLogs = logs.filter(l => l.medication_id === med.id);
              const firstLog = medLogs[medLogs.length-1];
              const daysSinceStart = firstLog ? Math.ceil((today-new Date(firstLog.taken_at).getTime())/86400000) : 0;
              const expectedDaily = med.times_per_day || 1;
              const expectedTotal = daysSinceStart * expectedDaily;
              const pct = expectedTotal > 0 ? Math.round((medLogs.length/expectedTotal)*100) : 0;
              const skipRate = medLogs.length > 0 ? Math.round((1 - medLogs.length/Math.max(expectedTotal,medLogs.length))*100) : 0;
              const trend = medLogs.length >= 14
                ? medLogs.slice(0,7).length >= medLogs.slice(-7).length ? "improving" : "declining"
                : "insufficient data";
              const trendColor = trend==="improving"?"var(--teal2)":trend==="declining"?"var(--red)":"var(--t3)";
              const trendIcon = trend==="improving"?<TrendingUp size={14} strokeWidth={2.2}/>:trend==="declining"?<TrendingDown size={14} strokeWidth={2.2}/>:<BarChart3 size={14} strokeWidth={2.2}/>;
              return (
                <div key={med.id} style={{background:"var(--card)",borderRadius:"var(--rl)",padding:14,boxShadow:"var(--card-shadow)"}}>
                  <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}>
                    <div style={{width:30,height:30,borderRadius:8,background:"var(--ib4)",display:"grid",placeItems:"center",flexShrink:0}}><Ico><BarChart3 size={16} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
                    <div>
                      <div style={{fontSize:15,fontWeight:600,color:"var(--t1)"}}>{med.name}</div>
                      <div style={{fontSize:12,color:"var(--t3)"}}>{medLogs.length} total doses · {pct}% adherence</div>
                    </div>
                  </div>
                  <div className="prog" style={{marginBottom:8}}><div className="prog-fill" style={{width:`${pct}%`,background:pct>=80?"var(--teal2)":pct>=50?"var(--orange)":"var(--red)"}}/></div>
                  <div style={{display:"flex",gap:16,fontSize:12}}>
                    <div style={{background:"var(--bg)",borderRadius:8,padding:"6px 10px",flex:1,textAlign:"center"}}>
                      <div style={{fontSize:11,color:"var(--t3)",marginBottom:1}}>Trend</div>
                      <div style={{fontWeight:600,color:trendColor,display:"flex",alignItems:"center",gap:4,justifyContent:"center"}}><Ico>{trendIcon}</Ico> {trend}</div>
                    </div>
                    <div style={{background:"var(--bg)",borderRadius:8,padding:"6px 10px",flex:1,textAlign:"center"}}>
                      <div style={{fontSize:11,color:"var(--t3)",marginBottom:1}}>Skip rate</div>
                      <div style={{fontWeight:600,color:"var(--t2)"}}>{skipRate}%</div>
                    </div>
                    <div style={{background:"var(--bg)",borderRadius:8,padding:"6px 10px",flex:1,textAlign:"center"}}>
                      <div style={{fontSize:11,color:"var(--t3)",marginBottom:1}}>Adherence</div>
                      <div style={{fontWeight:600,color:pct>=80?"var(--teal2)":pct>=50?"var(--orange)":"var(--red)"}}>{pct}%</div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {limits.reports && (
        <div className="section">
          <div className="section-header" style={{display:"flex",alignItems:"center",gap:8}}>
            <Ico><Lightbulb size={15} strokeWidth={2.2} color="var(--orange)"/></Ico> Treatment insights
          </div>
          <div style={{display:"flex",flexDirection:"column",gap:10}}>
            <div style={{background:"var(--card)",borderRadius:"var(--rl)",padding:14,boxShadow:"var(--card-shadow)",display:"flex",alignItems:"center",gap:12}}>
              <div style={{width:30,height:30,borderRadius:8,background:"var(--ib2)",display:"grid",placeItems:"center",flexShrink:0}}><Ico><Clock size={16} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
              <div style={{flex:1}}>
                <div style={{fontSize:15,fontWeight:600,color:"var(--t1)",marginBottom:2}}>Best time adherence</div>
                <div style={{fontSize:13,color:"var(--t3)"}}>
                  {logs.length > 0
                    ? (() => {
                        const hours = {};
                        logs.forEach(l => {
                          const h = new Date(l.taken_at).getHours();
                          const slot = h < 6 ? "Night" : h < 12 ? "Morning" : h < 18 ? "Afternoon" : "Evening";
                          hours[slot] = (hours[slot]||0)+1;
                        });
                        const bestSlot = Object.entries(hours).sort((a,b)=>b[1]-a[1])[0];
                        return `Most consistent in the ${bestSlot?.[0]||"day"} (${bestSlot?.[1]||0} doses)`;
                      })()
                    : "Log doses to see insights"}
                </div>
              </div>
            </div>
            <div style={{background:"var(--card)",borderRadius:"var(--rl)",padding:14,boxShadow:"var(--card-shadow)",display:"flex",alignItems:"center",gap:12}}>
              <div style={{width:30,height:30,borderRadius:8,background:"var(--ib3)",display:"grid",placeItems:"center",flexShrink:0}}><Ico><ClipboardList size={16} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
              <div style={{flex:1}}>
                <div style={{fontSize:15,fontWeight:600,color:"var(--t1)",marginBottom:2}}>Course completion forecast</div>
                <div style={{fontSize:13,color:"var(--t3)"}}>
                  {(() => {
                    const active = meds.filter(m=>m.active);
                    if (!active.length) return "No active courses";
                    const avg = active.reduce((s,m)=>{
                      const spent = Math.min(Math.ceil((today-new Date(m.start_date).getTime())/86400000), m.course_duration_days);
                      return s + (spent/m.course_duration_days);
                    },0)/active.length;
                    const pct = Math.round(avg*100);
                    return `${pct}% complete across ${active.length} active course${active.length>1?"s":""}`;
                  })()}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {plan==="family" && (
        <div className="section">
          <div className="section-header" style={{display:"flex",alignItems:"center",gap:8}}>
            <Ico><Users size={15} strokeWidth={2.2} color="var(--t1)"/></Ico> Caregiver dashboard
          </div>
          <div className="list">
            <div className="row" style={{cursor:"pointer"}} onClick={() => onViewFamily?.()}>
              <div className="row-icon" style={{background:"var(--ib4)"}}><Ico><User size={18} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
              <div className="row-body">
                <div className="row-title">Family members</div>
                <div className="row-sub">Manage up to {limits.profiles} profiles</div>
              </div>
              <span style={{fontSize:14,color:"var(--t3)"}}>›</span>
            </div>
            <div className="row" style={{cursor:"pointer"}} onClick={() => onViewFamily?.()}>
              <div className="row-icon" style={{background:"var(--ib2)"}}><Ico><BarChart3 size={18} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
              <div className="row-body">
                <div className="row-title">Shared reports</div>
                <div className="row-sub">View combined adherence across family members</div>
              </div>
              <span style={{fontSize:14,color:"var(--t3)"}}>›</span>
            </div>
            <div className="row" style={{cursor:"default"}}>
              <div className="row-icon" style={{background:"var(--ib3)"}}><Ico><Bell size={18} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
              <div className="row-body">
                <div className="row-title">Caregiver alerts</div>
                <div className="row-sub">Get notified when a loved one misses a dose</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {!limits.reports && (
        <div className="upgrade-card" style={{margin:"0 20px 16px"}}>
          <div className="upgrade-title">Upgrade for advanced reports</div>
          <div className="upgrade-sub">
            Get detailed per-medication analytics, treatment insights, skip-rate tracking and trend analysis with Pro.
          </div>
          <button className="upgrade-btn" onClick={() => onNavigate?.("profile")}>
            Go to Profile →
          </button>
        </div>
      )}

      <div style={{padding:"0 20px 16px"}}>
        <AdherenceChart logs={logs} meds={meds}/>
      </div>

      <div style={{padding:"0 20px 16px"}}>
        <SideEffectSummary meds={meds} logs={logs}/>
      </div>

      <div className="section" style={{margin:"0 20px 16px",padding:0}}>
          <div className="section-header" style={{display:"flex",alignItems:"center",gap:8}}>
            <Ico><DollarSign size={15} strokeWidth={2.2} color="var(--teal2)"/></Ico> Medication costs
          </div>
        <div style={{background:"var(--card)",borderRadius:16,padding:18,boxShadow:"var(--card-shadow)"}}>
          {(() => {
            const medsCosted = meds.filter(m => m.cost_per_package);
            if (!medsCosted.length) {
              return <div style={{textAlign:"center",padding:20,color:"var(--t3)",fontSize:13}}>Add cost info to your medications to track spending</div>;
            }
            const totalCost = medsCosted.reduce((s, m) => s + (Number(m.cost_per_package) || 0), 0);
            const currency = medsCosted[0]?.cost_currency || "GH₵";
            return (
              <>
                <div style={{textAlign:"center",marginBottom:20}}>
                  <div style={{fontSize:11,color:"var(--t3)",fontWeight:500,textTransform:"uppercase",letterSpacing:0.5,marginBottom:6}}>Total medication cost</div>
                  <div style={{fontSize:30,fontWeight:800,color:"var(--t1)",letterSpacing:-.5}}>{currency}{totalCost.toFixed(2)}</div>
                </div>
                {medsCosted.map(m => (
                  <div key={m.id} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderTop:"0.5px solid var(--sep)"}}>
                    <div style={{width:8,height:8,borderRadius:"50%",background:m.color||"var(--teal)",flexShrink:0}}/>
                    <div style={{flex:1}}>
                      <div style={{fontSize:13,fontWeight:500,color:"var(--t1)"}}>{m.name}</div>
                      <div style={{fontSize:11,color:"var(--t3)"}}>{m.pills_per_package ? `${m.pills_per_package} units/pkg` : "Per package"}</div>
                    </div>
                    <div style={{fontSize:14,fontWeight:700,color:"var(--t1)"}}>{m.cost_currency||currency}{Number(m.cost_per_package).toFixed(2)}</div>
                  </div>
                ))}
              </>
            );
          })()}
        </div>
      </div>

      <div className="section">
        <div className="section-header" style={{display:"flex",alignItems:"center",gap:8}}>
          <Ico><BookOpen size={15} strokeWidth={2.2} color="var(--purple)"/></Ico> Health journal
        </div>
        <div style={{padding:"0"}}>
          <JournalMiniCalendar entries={journalEntries} selectedDate={journalDate} onSelect={setJournalDate}/>
          {journalDate && <JournalEntrySheet date={journalDate} entry={getJournalEntry(journalDate)} onSave={() => { try { setJournalEntries(JSON.parse(localStorage.getItem("mt_journal") || "[]")); } catch {} }} onClose={() => setJournalDate(null)}/>}
          <JournalTimeline entries={journalEntries}/>
        </div>
      </div>

      <div className="section">
        <div className="section-header" style={{display:"flex",alignItems:"center",gap:8,cursor:"pointer",userSelect:"none"}} onClick={() => setShowHistory(!showHistory)}>
          <Ico><ClipboardList size={15} strokeWidth={2.2} color="var(--t1)"/></Ico> Dose history
          <span style={{marginLeft:"auto",fontSize:12,color:"var(--t3)",transition:"transform .2s",transform:showHistory?"rotate(180deg)":"rotate(0deg)"}}>▼</span>
        </div>
        {showHistory && (() => {
          const limits2 = { free: { history: 7 }, pro: { history: 999 }, family: { history: 999 } };
          const maxDays = (limits2[plan] || limits2.free).history;
          const grouped2 = {};
          logs.forEach(l => {
            const d = l.taken_at?.split("T")[0];
            if (d) { if (!grouped2[d]) grouped2[d] = []; grouped2[d].push(l); }
          });
          const days = Object.keys(grouped2).sort().reverse().slice(0, maxDays);
          const totalExpected = meds.reduce((s, m) => s + (m.times_per_day || 1), 0);

          if (days.length === 0) {
            return <div className="empty-state" style={{marginBottom:8}}><div className="empty-state-icon"><Ico><ClipboardList size={52} strokeWidth={1.5} color="var(--t2)"/></Ico></div><div className="empty-state-title">No history yet</div><div className="empty-state-sub">Your dose logs will appear here</div></div>;
          }

          return days.map(d => {
            const dayLogs = grouped2[d];
            const dayPct = totalExpected > 0 ? Math.min(Math.round(dayLogs.length / totalExpected * 100), 100) : 0;
            return (
              <div key={d} style={{marginBottom:12}}>
                <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:6,paddingLeft:4}}>
                  <div style={{width:8,height:8,borderRadius:"50%",background:"var(--teal)",flexShrink:0}}/>
                  <div style={{fontSize:14,fontWeight:600,color:"var(--t1)",letterSpacing:"-.2px"}}>{fmtDateLong(d+"T12:00:00")}</div>
                  <div style={{marginLeft:"auto",fontSize:11,color:"var(--t3)",background:"var(--bg)",padding:"2px 10px",borderRadius:99}}>{dayLogs.length} dose{dayLogs.length!==1?"s":""}</div>
                </div>
                <div style={{background:"var(--card)",borderRadius:"var(--rl)",overflow:"hidden",boxShadow:"var(--card-shadow)"}}>
                  {dayLogs.map((log, i) => (
                    <div key={log.id} className="row" style={{borderTop:i>0?"0.5px solid var(--sep)":"none",cursor:"default"}}>
                      <div style={{width:28,height:28,borderRadius:7,background:"var(--ib1)",display:"grid",placeItems:"center",flexShrink:0}}><Ico><Pill size={14} strokeWidth={2.2} color="var(--t1)"/></Ico></div>
                      <div className="row-body">
                        <div className="row-title" style={{fontSize:14}}>{log.medications?.name || "Medication"}</div>
                        {log.journal && <div className="row-sub" style={{fontSize:11,display:"flex",alignItems:"center",gap:4}}><Ico><FileText size={11} strokeWidth={2.2}/></Ico> {log.journal.slice(0, 40)}{log.journal.length > 40 ? "…" : ""}</div>}
                      </div>
                      <span style={{fontSize:12,fontWeight:500,color:"var(--t2)",background:"var(--bg)",padding:"3px 10px",borderRadius:99}}>{fmtTime(log.taken_at)}</span>
                    </div>
                  ))}
                </div>
                <div style={{marginTop:6,padding:"0 4px",display:"flex",alignItems:"center",gap:8}}>
                  <div style={{flex:1,height:4,borderRadius:2,background:"var(--sep)",overflow:"hidden"}}>
                    <div style={{width:`${dayPct}%`,height:"100%",borderRadius:2,background:dayPct>=80?"var(--teal2)":dayPct>=50?"var(--orange)":"var(--red)",transition:"width .4s"}}/>
                  </div>
                  <span style={{fontSize:11,fontWeight:600,color:dayPct>=80?"var(--teal2)":dayPct>=50?"var(--orange)":"var(--red)"}}>{dayPct}%</span>
                </div>
              </div>
            );
          });
        })()}
      </div>

      <div style={{padding:"4px 20px 20px",display:"flex",gap:10}}>
        <button className="btn btn-primary" onClick={generatePdfReport} disabled={meds.length === 0} style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>
          <Ico><FileText size={15} strokeWidth={2.2} color="white"/></Ico> Generate PDF report
        </button>
        <button className="btn" onClick={shareWithDoctor} disabled={meds.length === 0}
          style={{flex:1,background:"var(--teal2)",color:"white",fontWeight:600,display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>
          <Ico><Stethoscope size={15} strokeWidth={2.2} color="white"/></Ico> Share with doctor
        </button>
      </div>

      <div style={{padding:"4px 20px 20px",display:"flex",gap:10}}>
        <button className="btn" onClick={() => exportCsv("dose_logs", logs, meds)}
          style={{flex:1,background:"var(--card)",color:"var(--t1)",fontWeight:500,display:"flex",alignItems:"center",justifyContent:"center",gap:6,border:"0.5px solid var(--sep)"}}>
          <Ico><Download size={15} strokeWidth={2.2}/></Ico> Export CSV
        </button>
        <button className="btn" onClick={exportJournalCsv}
          style={{flex:1,background:"var(--card)",color:"var(--t1)",fontWeight:500,display:"flex",alignItems:"center",justifyContent:"center",gap:6,border:"0.5px solid var(--sep)"}}>
          <Ico><Download size={15} strokeWidth={2.2}/></Ico> Export journal
        </button>
      </div>
    </div>
  );
}

function exportCsv(name, logs, meds) {
  const medMap = {};
  meds.forEach(m => { medMap[m.id] = m.name; });
  const header = "Date,Time,Medication,Dosage,Journal\n";
  const rows = [...logs].reverse().map(l => {
    const d = new Date(l.taken_at);
    const date = d.toISOString().split("T")[0];
    const time = d.toTimeString().split(" ")[0].slice(0, 5);
    const medName = medMap[l.medication_id] || "Unknown";
    const dosage = l.medications ? `${l.medications.dosage_amount} ${l.medications.dosage_unit}` : "";
    const journal = (l.journal || "").replace(/"/g, '""');
    return `"${date}","${time}","${medName}","${dosage}","${journal}"`;
  }).join("\n");
  downloadCsv(header + rows, `${name}_${new Date().toISOString().split("T")[0]}.csv`);
}

function exportJournalCsv() {
  let entries = [];
  try { entries = JSON.parse(localStorage.getItem("mt_journal") || "[]"); } catch {}
  const header = "Date,Entry,Mood\n";
  const rows = entries.map(e => {
    const date = e.date || "";
    const text = (e.text || e.entry || "").replace(/"/g, '""');
    const mood = e.mood || "";
    return `"${date}","${text}","${mood}"`;
  }).join("\n");
  downloadCsv(header + rows, `journal_${new Date().toISOString().split("T")[0]}.csv`);
}

function downloadCsv(content, filename) {
  const blob = new Blob([content], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
